/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResearchImport } from './routes/research'
import { Route as ProductivityImport } from './routes/productivity'
import { Route as FileUtilsImport } from './routes/file-utils'
import { Route as CreateImport } from './routes/create'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ResearchRoute = ResearchImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRoute,
} as any)

const ProductivityRoute = ProductivityImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => rootRoute,
} as any)

const FileUtilsRoute = FileUtilsImport.update({
  id: '/file-utils',
  path: '/file-utils',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/file-utils': {
      id: '/file-utils'
      path: '/file-utils'
      fullPath: '/file-utils'
      preLoaderRoute: typeof FileUtilsImport
      parentRoute: typeof rootRoute
    }
    '/productivity': {
      id: '/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ProductivityImport
      parentRoute: typeof rootRoute
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/file-utils': typeof FileUtilsRoute
  '/productivity': typeof ProductivityRoute
  '/research': typeof ResearchRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/file-utils': typeof FileUtilsRoute
  '/productivity': typeof ProductivityRoute
  '/research': typeof ResearchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/file-utils': typeof FileUtilsRoute
  '/productivity': typeof ProductivityRoute
  '/research': typeof ResearchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/file-utils' | '/productivity' | '/research'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/file-utils' | '/productivity' | '/research'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/file-utils'
    | '/productivity'
    | '/research'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  FileUtilsRoute: typeof FileUtilsRoute
  ProductivityRoute: typeof ProductivityRoute
  ResearchRoute: typeof ResearchRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  FileUtilsRoute: FileUtilsRoute,
  ProductivityRoute: ProductivityRoute,
  ResearchRoute: ResearchRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create",
        "/file-utils",
        "/productivity",
        "/research"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/file-utils": {
      "filePath": "file-utils.tsx"
    },
    "/productivity": {
      "filePath": "productivity.tsx"
    },
    "/research": {
      "filePath": "research.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
